# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(720, 620)
        LoginForm.setMinimumSize(QtCore.QSize(0, 0))
        LoginForm.setMaximumSize(QtCore.QSize(1000, 1000))
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(LoginForm)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_top_bg_label = QtWidgets.QLabel(self.widget)
        self.login_top_bg_label.setObjectName("login_top_bg_label")
        self.horizontalLayout_2.addWidget(self.login_top_bg_label)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(LoginForm)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.url_pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_pushButton.sizePolicy().hasHeightForWidth())
        self.url_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.url_pushButton.setFont(font)
        self.url_pushButton.setFlat(True)
        self.url_pushButton.setObjectName("url_pushButton")
        self.horizontalLayout.addWidget(self.url_pushButton, 0, QtCore.Qt.AlignBottom)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.remember_passwd_checkBox = QtWidgets.QCheckBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remember_passwd_checkBox.sizePolicy().hasHeightForWidth())
        self.remember_passwd_checkBox.setSizePolicy(sizePolicy)
        self.remember_passwd_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.remember_passwd_checkBox.setFont(font)
        self.remember_passwd_checkBox.setStyleSheet("QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}")
        self.remember_passwd_checkBox.setObjectName("remember_passwd_checkBox")
        self.gridLayout.addWidget(self.remember_passwd_checkBox, 4, 1, 1, 1, QtCore.Qt.AlignRight)
        self.login_pushButton = QtWidgets.QPushButton(self.widget_3)
        self.login_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_pushButton.sizePolicy().hasHeightForWidth())
        self.login_pushButton.setSizePolicy(sizePolicy)
        self.login_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.login_pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_pushButton.setFont(font)
        self.login_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    spacing: 500px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(85,85,255);\n"
"}\n"
"")
        self.login_pushButton.setObjectName("login_pushButton")
        self.gridLayout.addWidget(self.login_pushButton, 5, 0, 1, 2)
        self.Auto_login_checkBox = QtWidgets.QCheckBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Auto_login_checkBox.sizePolicy().hasHeightForWidth())
        self.Auto_login_checkBox.setSizePolicy(sizePolicy)
        self.Auto_login_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.Auto_login_checkBox.setFont(font)
        self.Auto_login_checkBox.setStyleSheet("QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}")
        self.Auto_login_checkBox.setIconSize(QtCore.QSize(16, 16))
        self.Auto_login_checkBox.setObjectName("Auto_login_checkBox")
        self.gridLayout.addWidget(self.Auto_login_checkBox, 4, 0, 1, 1)
        self.username_lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.username_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.username_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setStyleSheet("QLineEdit {\n"
"    font-size: 15pt;\n"
"    border: none;\n"
"    border-bottom: 1px solid lightgray;\n"
"    background-color: transparent;\n"
"}\n"
"QLineEdit:hover {\n"
"    border-bottom:1px solid gray;\n"
"}\n"
"QLineEdit:focus {\n"
"border-bottom: 1px solid rgb(18,183,245);\n"
"}")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.gridLayout.addWidget(self.username_lineEdit, 1, 0, 1, 2)
        self.passwd_lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.passwd_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.passwd_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.passwd_lineEdit.setFont(font)
        self.passwd_lineEdit.setStyleSheet("QLineEdit {\n"
"    font-size: 15pt;\n"
"    border: none;\n"
"    border-bottom: 1px solid lightgray;\n"
"    background-color: transparent;\n"
"}\n"
"QLineEdit:hover {\n"
"    border-bottom:1px solid gray;\n"
"}\n"
"QLineEdit:focus {\n"
"border-bottom: 1px solid rgb(18,183,245);\n"
"}")
        self.passwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd_lineEdit.setClearButtonEnabled(True)
        self.passwd_lineEdit.setObjectName("passwd_lineEdit")
        self.gridLayout.addWidget(self.passwd_lineEdit, 3, 0, 1, 2)
        self.horizontalLayout.addWidget(self.widget_3)
        self.config_pushButton = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_pushButton.sizePolicy().hasHeightForWidth())
        self.config_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.config_pushButton.setFont(font)
        self.config_pushButton.setFlat(True)
        self.config_pushButton.setObjectName("config_pushButton")
        self.horizontalLayout.addWidget(self.config_pushButton, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 6)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 5)

        self.retranslateUi(LoginForm)
        self.url_pushButton.clicked.connect(LoginForm.open_url_link)
        self.passwd_lineEdit.textChanged['QString'].connect(LoginForm.enable_login_btn)
        self.login_pushButton.clicked.connect(LoginForm.ckeck_login)
        self.Auto_login_checkBox.clicked['bool'].connect(LoginForm.auto_login)
        self.remember_passwd_checkBox.clicked['bool'].connect(LoginForm.remember_pwd)
        self.username_lineEdit.textChanged['QString'].connect(LoginForm.enable_login_btn)
        self.config_pushButton.clicked.connect(LoginForm.open_config_pane)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.login_top_bg_label.setText(_translate("LoginForm", "TextLabel"))
        self.url_pushButton.setText(_translate("LoginForm", "网页登录"))
        self.remember_passwd_checkBox.setText(_translate("LoginForm", "记住密码"))
        self.login_pushButton.setText(_translate("LoginForm", "登录"))
        self.Auto_login_checkBox.setText(_translate("LoginForm", "自动登录"))
        self.config_pushButton.setText(_translate("LoginForm", "配置信息"))
